spring.application.name=phantasmon-backend

spring.datasource.url=jdbc:postgresql://${BDD_HOST:localhost}:${BDD_PORT:5432}/${BDD_NAME:db_phantasmon}
spring.datasource.username=${BDD_USER}
spring.datasource.password=${BDD_PASSWORD}

spring.jpa.hibernate.ddl-auto=none
spring.jpa.open-in-view=false
spring.jpa.properties.hibernate.jdbc.time_zone=UTC
