package com.mystaria.phantasmon_backend.hub;

import java.nio.file.Files;
import java.nio.file.Path;
import java.util.UUID;

import org.junit.jupiter.api.Test;
import org.junit.jupiter.api.io.TempDir;

import static org.assertj.core.api.Assertions.assertThat;
import static org.assertj.core.api.Assertions.assertThatThrownBy;

/**
 * A hub's build (D-34, D-35): at most one {@code .schem} / {@code .litematic} in its folder, of the hub's size, or the
 * backend refuses to start (a reload refuses it the same way); an empty folder is a hub without a build. Fixtures
 * generated by {@code scripts/generate_hub_schematics.py}; plus the boxes anchors occupy.
 */
class HubCatalogSchematicTest {

	private static final Path FIXTURES = Path.of("src/test/resources/schematics");
	private static final Hub ARENA = new Hub(UUID.randomUUID(), "arena", 21, 21, 21, null);

	@TempDir
	Path dir;

	private Path copy(String fixture, String as) throws Exception {
		Files.copy(FIXTURES.resolve(fixture), dir.resolve(as));
		return dir;
	}

	@Test
	void readsTheSizeOfEachFormat() throws Exception {
		for (String fixture : new String[] { "room_v2.schem", "room_v3.schem", "room.litematic" }) {
			byte[] bytes = Files.readAllBytes(FIXTURES.resolve(fixture));
			HubCatalogService.Format format = fixture.endsWith(".litematic") ? HubCatalogService.Format.LITEMATIC
					: HubCatalogService.Format.SCHEM;
			assertThat(HubCatalogService.dimensions(NbtReader.read(bytes), format)).as(fixture).containsExactly(3, 2, 4);
		}
	}

	@Test
	void loadsTheOneSchematicOfTheHubsSizeOrNoneFromAnEmptyFolder() throws Exception {
		assertThat(HubCatalogService.load(dir, ARENA)).isEmpty();
		copy("arena.litematic", "arena.litematic");
		Files.writeString(dir.resolve("readme.txt"), "ignored");
		HubCatalogService.Schematic schematic = HubCatalogService.load(dir, ARENA).orElseThrow();
		assertThat(schematic.fileName()).isEqualTo("arena.litematic");
		assertThat(schematic.format()).isEqualTo(HubCatalogService.Format.LITEMATIC);
		assertThat(schematic.sizeX()).isEqualTo(21);
		assertThat(schematic.sha256()).hasSize(64);

		Path room = Files.createDirectories(dir.resolve("room"));
		Files.copy(FIXTURES.resolve("room_v3.schem"), room.resolve("room.schem"));
		assertThat(HubCatalogService.load(room, new Hub(UUID.randomUUID(), "room", 3, 2, 4, null))).isPresent();
	}

	@Test
	void refusesTwoFilesAWrongSizeOrAnUnreadableFile() throws Exception {
		copy("arena.litematic", "a.litematic");
		copy("arena_v3.schem", "b.schem");
		assertThatThrownBy(() -> HubCatalogService.load(dir, ARENA))
				.isInstanceOf(IllegalStateException.class).hasMessageContaining("found 2");

		Path room = Files.createDirectories(dir.resolve("room"));
		Files.copy(FIXTURES.resolve("room_v3.schem"), room.resolve("room.schem"));
		assertThatThrownBy(() -> HubCatalogService.load(room, ARENA))
				.isInstanceOf(IllegalStateException.class).hasMessageContaining("3x2x4");

		Path broken = Files.createDirectories(dir.resolve("broken"));
		Files.writeString(broken.resolve("hub.schem"), "not nbt");
		assertThatThrownBy(() -> HubCatalogService.load(broken, ARENA))
				.isInstanceOf(IllegalStateException.class).hasMessageContaining("cannot be read");
	}

	@Test
	void anAnchorsBoxIsCentredOnItsBlockAndTurnsWithIt() {
		// Same expectations as the client's HubBuildLayout: 21 wide around x = 100, from the feet up.
		assertThat(HubBox.of(100.7, 64.0, -20.2, 0, 21, 21, 21)).isEqualTo(new HubBox(90, 64, -31, 110, 84, -11));
		// 3 wide, 15 long: facing south it runs along z, facing west along x.
		assertThat(HubBox.of(0.5, 64.0, 0.5, 0, 3, 3, 15)).isEqualTo(new HubBox(-1, 64, -7, 1, 66, 7));
		assertThat(HubBox.of(0.5, 64.0, 0.5, 90, 3, 3, 15)).isEqualTo(new HubBox(-7, 64, -1, 7, 66, 1));
		assertThat(HubBox.of(0.5, 64.5, 0.5, 0, 3, 3, 3).minY()).isEqualTo(65);
		assertThat(HubBox.of(0, 64, 0, 0, 3, 3, 3).intersects(HubBox.of(2, 66, 0, 0, 3, 3, 3))).isTrue();
		assertThat(HubBox.of(0, 64, 0, 0, 3, 3, 3).intersects(HubBox.of(3, 64, 0, 0, 3, 3, 3))).isFalse();
		assertThat(HubBox.of(0, 64, 0, 0, 3, 3, 3).intersects(HubBox.of(0, 67, 0, 0, 3, 3, 3))).isFalse();
	}
}
