package com.mystaria.phantasmon_backend.hub;

import java.nio.file.Files;
import java.nio.file.Path;

import org.junit.jupiter.api.Test;
import org.junit.jupiter.api.io.TempDir;

import static org.assertj.core.api.Assertions.assertThat;
import static org.assertj.core.api.Assertions.assertThatThrownBy;

/**
 * The Global Hub's build (D-34): exactly one {@code .schem} / {@code .litematic} in {@code hub_global/}, the size of an
 * anchor, or the backend refuses to start. Fixtures generated by {@code scripts/generate_hub_schematics.py}.
 */
class HubSchematicServiceTest {

	private static final Path FIXTURES = Path.of("src/test/resources/schematics");

	@TempDir
	Path dir;

	private Path folder() throws Exception {
		return Files.createDirectories(dir.resolve(HubSchematicService.GLOBAL_HUB_FOLDER));
	}

	private void copy(String fixture, String as) throws Exception {
		Files.copy(FIXTURES.resolve(fixture), folder().resolve(as));
	}

	@Test
	void readsTheSizeOfEachFormat() throws Exception {
		for (String fixture : new String[] { "room_v2.schem", "room_v3.schem", "room.litematic" }) {
			byte[] bytes = Files.readAllBytes(FIXTURES.resolve(fixture));
			HubSchematicService.Format format = fixture.endsWith(".litematic") ? HubSchematicService.Format.LITEMATIC
					: HubSchematicService.Format.SCHEM;
			assertThat(HubSchematicService.dimensions(NbtReader.read(bytes), format)).as(fixture).containsExactly(3, 2, 4);
		}
	}

	@Test
	void loadsTheOneSchematicOfTheAnchorsSize() throws Exception {
		copy("arena.litematic", "arena.litematic");
		Files.writeString(folder().resolve("readme.txt"), "ignored");
		HubSchematicService.Schematic schematic = HubSchematicService.load(folder(), 21);
		assertThat(schematic.fileName()).isEqualTo("arena.litematic");
		assertThat(schematic.format()).isEqualTo(HubSchematicService.Format.LITEMATIC);
		assertThat(schematic.sizeX()).isEqualTo(21);
		assertThat(schematic.sha256()).hasSize(64);
		assertThat(schematic.bytes()).isEqualTo(Files.readAllBytes(FIXTURES.resolve("arena.litematic")));

		Path v3 = Files.createDirectories(dir.resolve("v3").resolve(HubSchematicService.GLOBAL_HUB_FOLDER));
		Files.copy(FIXTURES.resolve("arena_v3.schem"), v3.resolve("arena.schem"));
		assertThat(HubSchematicService.load(v3, 21).format()).isEqualTo(HubSchematicService.Format.SCHEM);
	}

	@Test
	void refusesAMissingFolderNoFileOrTwoFiles() throws Exception {
		assertThatThrownBy(() -> HubSchematicService.load(dir.resolve("nowhere"), 21))
				.isInstanceOf(IllegalStateException.class).hasMessageContaining("missing");
		assertThatThrownBy(() -> HubSchematicService.load(folder(), 21))
				.isInstanceOf(IllegalStateException.class).hasMessageContaining("found 0");
		copy("arena.litematic", "a.litematic");
		copy("arena_v3.schem", "b.schem");
		assertThatThrownBy(() -> HubSchematicService.load(folder(), 21))
				.isInstanceOf(IllegalStateException.class).hasMessageContaining("found 2");
	}

	@Test
	void refusesAWrongSizeOrAnUnreadableFile() throws Exception {
		copy("room_v3.schem", "room.schem");
		assertThatThrownBy(() -> HubSchematicService.load(folder(), 21))
				.isInstanceOf(IllegalStateException.class).hasMessageContaining("3x2x4");

		Path broken = Files.createDirectories(dir.resolve("broken").resolve(HubSchematicService.GLOBAL_HUB_FOLDER));
		Files.writeString(broken.resolve("hub.schem"), "not nbt");
		assertThatThrownBy(() -> HubSchematicService.load(broken, 21))
				.isInstanceOf(IllegalStateException.class).hasMessageContaining("cannot be read");
	}
}
