package com.mystaria.phantasmon_backend.player;

import java.time.Instant;
import java.util.UUID;

import jakarta.persistence.Column;
import jakarta.persistence.Entity;
import jakarta.persistence.Id;
import jakarta.persistence.Table;

import lombok.AccessLevel;
import lombok.Getter;
import lombok.NoArgsConstructor;
import lombok.Setter;

/**
 * Minimal identity of a Minecraft player known to Phantasmon (CAD Partie 2 §5.1,
 * PHANTASMON_DB_SCHEMA.md §3). {@code uuid} is the real Mojang account UUID,
 * never generated by the backend.
 */
@Entity
@Table(name = "players")
@Getter
@NoArgsConstructor(access = AccessLevel.PROTECTED)
public class Player {

	@Id
	private UUID uuid;

	@Setter
	@Column(name = "last_username", nullable = false, length = 16)
	private String lastUsername;

	@Column(name = "created_at", nullable = false, updatable = false)
	private Instant createdAt;

	@Setter
	@Column(name = "last_seen_at")
	private Instant lastSeenAt;

	Player(UUID uuid, String lastUsername, Instant createdAt, Instant lastSeenAt) {
		this.uuid = uuid;
		this.lastUsername = lastUsername;
		this.createdAt = createdAt;
		this.lastSeenAt = lastSeenAt;
	}
}
